# Generated by Django 5.1.1 on 2024-09-30 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_role_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberimage_set', to='member.member'),
        ),
    ]
