# Generated by Django 5.1.1 on 2024-10-02 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationtoken_user_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_verification', to='accounts.verificationtoken'),
        ),
    ]
