# Generated by Django 5.1.1 on 2024-09-28 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='up_coming',
            field=models.BooleanField(default=False),
        ),
    ]
