# Generated by Django 5.1.1 on 2024-09-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_services_app_up_coming'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
