# Generated by Django 5.1.1 on 2024-09-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
