# Generated by Django 5.1.1 on 2024-09-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_app_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='url',
            new_name='url_name',
        ),
    ]
